# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
    # Set the job key. The key is displayed as the job name
    # when a job name is not provided
    test:
        name: Run tests
        # Set the type of machine to run on
        runs-on: ubuntu-latest
        steps:
            # Checks out a copy of your repository on the ubuntu-latest machine
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup raku
              uses: Raku/setup-raku@v1  # By default, this sets up the latest rakudo
            - name: Install module dependencies
              run: zef install --deps-only . --force-test
            - name: Run tests
              run: ./run-tests
